service: phront-data-worker

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev # Set the default stage used. Default is dev
  profile: phront-code
  role: arn:aws:iam::537014313177:role/phront-data-service
  region: us-west-2 # Overwrite the default region used. Default is us-east-1
  websocketsApiName: phront-data-worker
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  environment:
    APIG_ENDPOINT:
      Fn::Join:
        - ''
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:custom.stage}
    CONNECTIONS_TABLE:
      Ref: ConnectionsTable


functions:
  connect:
    handler: handler.connect
    events:
      - websocket:
          route: $connect # authorizers are only for connect routes
          # authorizer:
          #   name: auth
          #   identitySource:
          #     - 'route.request.header.Auth'
  default:
    handler: handler.default
    events:
      - websocket:
          route: $default

  # auth:
  #   handler: handler.auth